### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by fusionstrings** [jaebradley/fruit#34]
I am getting following error after installing globally as mentioned in readme, and running the command `fruit`.

I am getting following error

```sh
➜  rollup-lab fruit
module.js:549
    throw err;
    ^

Error: Cannot find module '@babel/runtime/core-js/object/freeze'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dilip/.nvm/versions/node/v8.11.3/lib/node_modules/@jaebradley/fruit/build/executor.js:12:38)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by jaebradley** [comment]
@fusionstrings does this issue resolve after installing `v1.0.18`?

**Comment by fusionstrings** [comment]
WOW, it works thanks a lot 💯

**Comment by fusionstrings** [comment]
or, maybe not. After scaffolding while installing dependencies, it throws following 

```sh
➜  rollup-lab fruit
? 📦  Select a package type React
? ✅  Select package features commitlint, semantic-release
? 📛  Input a package name rollup-lab
? 🏷️  Input a package description rollup experiment
? 🌱  Input an initial package version 0.1.0
? 📍  Input the relative package location src/main.js
? 📥  Input your email address fusionstrings@gmail.com
? 👤  Input your GitHub username fusionstrings
⌛ 🤞 Installing packages
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> fsevents@1.2.4 install /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/fsevents
> node install

[fsevents] Success: "/Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> husky@0.14.3 install /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
can't find .git directory, skipping Git hooks installation

> node-sass@4.9.3 install /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/darwin-x64-57_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Caching binary to /Users/dilip/.npm/node-sass/4.9.3/darwin-x64-57_binding.node

> axe-core@2.6.1 postinstall /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/axe-core
> node build/utils/postinstall.js


> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.3 postinstall /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> rollup-lab@0.1.0 prepare /Users/dilip/git/lab/rollup-lab/src/main.js
> npm run build:prod


> rollup-lab@0.1.0 build:prod /Users/dilip/git/lab/rollup-lab/src/main.js
> BABEL_ENV=production npm run build


> rollup-lab@0.1.0 build /Users/dilip/git/lab/rollup-lab/src/main.js
> rollup -c

[!] Error: Cannot find module 'rollup-plugin-uglify'
Error: Cannot find module 'rollup-plugin-uglify'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dilip/git/lab/rollup-lab/src/main.js/rollup.config.js:13:30)
    at Module._compile (module.js:652:30)
    at Object.require.extensions..js (/Users/dilip/git/lab/rollup-lab/src/main.js/node_modules/rollup/bin/rollup:2914:24)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rollup-lab@0.1.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rollup-lab@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dilip/.npm/_logs/2018-08-10T20_09_44_770Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rollup-lab@0.1.0 build:prod: `BABEL_ENV=production npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rollup-lab@0.1.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dilip/.npm/_logs/2018-08-10T20_09_44_859Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rollup-lab@0.1.0 prepare: `npm run build:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rollup-lab@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dilip/.npm/_logs/2018-08-10T20_09_45_407Z-debug.log
(node:61962) UnhandledPromiseRejectionWarning: ChildProcessError: `npm install` failed with code 1
    at ChildProcess.<anonymous> (/Users/dilip/.nvm/versions/node/v8.11.3/lib/node_modules/@jaebradley/fruit/node_modules/child-process-promise/lib/index.js:132:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:61962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whichwas not handled with .catch(). (rejection id: 1)
(node:61962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
